---
title: "survival-figs"
author: "Kylie Newcomer"
format: html
editor: visual
execute:
  message: false
  warning: false
---

```{r}
library(tidyverse)
library(rgl)
library(naniar)
library(purrr)
library(gganimate)
library(here)
```

```{r}
coral <- read_csv(here("..", "eds-coral-data-storage-management", "data", "volume_corals.csv"))

source(here("survival", "R", "survival_fig_function.R"))
```

```{r}
# Initalize coral color palette
coral_colors <- c(
    Acr = "blue", 
    Poc = "red", 
    Por = "darkgreen", 
    Mil = "darkorange"
  )

coral_death <- coral %>% 
  group_by(coral_number) %>%
  arrange(year) %>% 
  mutate(survival = case_when(
    dyn_death == 1 ~ 0,
    is.na(length) ~ NA,
    TRUE ~ 1
  ), volume = case_when(
    is.na(size_t0) ~ size_t_minus1,
    TRUE~ size_t0
  )
  ) %>% 
  ungroup()

```

```{r}
survival_plot(data = coral_death, site = "LTER4", habitat = "OR")
```

```{r}
survival_plot(data = coral_death, site = "LTER1")
```

\<\<\<\<\<\<\< HEAD

```{r}
survival_habitat <- survival_plot(data = coral_death, site ==)

ggsave("survival_habitat.png", survival_habitat, width = 9, height = 5)
```

```{r}
survival_habitat <- 
  ggplot(coral_death, aes(volume, survival, color = taxa)) +
      geom_point(alpha = 0.4) +
      scale_color_manual(values = coral_colors) +
      facet_grid(habitat~taxa, scales = "free") +
      scale_y_continuous(labels = scales::percent) +
  
      labs(title = paste("Coral survivorship by habitat (2013-2024)"),
           y = "Probability of survival",
           x = bquote("Initial volume" ~(cm^3))) +
      theme_light() +
      theme(legend.position = "none",
            axis.text.x = element_text(size = 6, angle = 45, hjust = 1))

#ggsave("survival_habitat.png", survival_habitat, width = 9, height = 5)
```

```{r}
survival_plot(coral_death, site = "LTER1", habitat = "OR")
```

```{r}
library(ggtext)
habitat_labels <- c("BR" = "Back Reef", "OR" = "Fore Reef")

taxa_labels <- c("Acr" = "*Acropora*", "Mil" = "*Millepora*",
                 "Poc" = "*Pocillopora*", "Por" = "*Porites*")
survival_habitat <-
  coral_death %>% 
  filter(site == "LTER1") %>% 
  ggplot(aes(volume, survival, color = taxa)) +
    geom_point(alpha = 0.4) +
    scale_color_manual(values = coral_colors) +
  scale_x_log10(breaks = 10^(-1:5), labels = scales::label_log()) +
    facet_grid(habitat ~ taxa,
               labeller = labeller(habitat = habitat_labels,
                                   taxa = taxa_labels),
                          drop = FALSE) +
    #scale_y_continuous(labels = scales::percent) +
    labs(y = "Probability of survival",
         x = "Initial volume (cm³)") +
    theme_light() +
    theme(
      legend.position = "none",
      axis.text.x = element_text(size = 6, angle = 45, hjust = 1),
            strip.background = element_rect(fill = "black"),
            strip.text.x = element_text(color = "white"),
            strip.text.y = element_markdown(color = "white"),
            panel.background = element_rect(fill = "transparent"),
            plot.background = element_rect(fill = "transparent"))

ggsave(here::here("img", "survival_habitat.png"),
       height = 4, width = 8.5, bg = "transparent")
```
