---
title: "animated_figure_drafts"
format: html
---

```{r}
library(tidyverse)
library(gganimate)
library(rlang)
library(gifski)
library(magick)
```

```{r}
coral <- read_csv(here::here("..", "eds-coral-data-storage-management", "analysisdata", "coral_demography_analysis_data.csv"), guess_max = 10000)
```
```{r}
# coral_colors <- c(
#     Acr = "blue", 
#     Poc = "red", 
#     Por = "darkgreen", 
#     Mil = "darkorange",
#     dead = "grey"
#   )
coral_colors <- c(
  "Poc" = "#F4A6C0",  # light pink
  "Por" = "#D4A017",  # gold
  "Acr" = "#E63946",  # light red
   "Mil" = "#FF7F2A",
    "Dead" = "grey2",
  "Recruit" = "green"
)


```

```{r}
coral_death <- coral %>% 
  group_by(coral_id) %>%
  arrange(coral_id, year) %>% 
  mutate(current_volume = case_when(
    is.na(size_t0) ~ size_t_minus1,
    TRUE~ size_t0
  ),
  survival = case_when(
    dyn_death == 1 ~ 0,
    is.na(l) ~ NA,
    TRUE ~ 1
  )) %>% 
  ungroup()
```

```{r}
coral_dyn <- coral_death %>% 
  mutate(taxa_class = case_when(
    dyn_death == 1 ~ "Dead",
    dyn_recruitment == 1 ~ "Recruit",
    TRUE ~ taxa
  ))
```

Create figure
```{r}
plot <- coral_dyn %>% 
  filter(site == "LTER1" &
           habitat == "BR" & 
           transect == "T01" &
           !is.na(current_volume)
         ) %>% 
  mutate(y_m = y / 100) %>% 
  ggplot(aes(x, y_m)) +
  #geom_point(aes(color = taxa_class, size = current_volume * 2, group = coral_id)) + # Add rings for recruitment and death
  geom_point(shape = 21, aes(color = taxa_class, fill = taxa, size = current_volume, group = coral_id)) +
  scale_size(range = c(0.01, 5), 
           name = "Volume (cm³)") +
  scale_color_manual(values = coral_colors) +
  scale_fill_manual(values = coral_colors) +
  theme_light() +
  coord_fixed(ratio = 1) +
  labs(title = 'LTER 1 lagoon transect 1 coral population year: {closest_state}',
       x = "Transect length (m)",
       y = "Transect width (m)") +
  transition_states(year,
    transition_length = 4,
    state_length = 2) +
  theme_bw() +
  theme(legend.position = "none",
        title = element_text(size = 8),
        axis.title = element_text(size = 6))

anim <- animate(plot,
        duration = 30,
        fps = 25, height = 500, width = 2500, res = 300,
        renderer = gifski_renderer())

magick::image_read(anim) %>%
  magick::image_trim() %>%          # auto-trims white borders
  magick::image_write_gif("coral_trimmed.gif")
```

```{r}
gif_maker(data = coral_dyn, lter_site = "LTER1", habitat_code = "BR", transect_number = "T01")

gif_maker(data = coral_dyn, lter_site = "LTER1", habitat_code = "BR", transect_number = "T02")

gif_maker(data = coral_dyn, lter_site = "LTER1", habitat_code = "BR", transect_number = "T03")

gif_maker(data = coral_dyn, lter_site = "LTER1", habitat_code = "BR", transect_number = "T04")

gif_maker(data = coral_dyn, lter_site = "LTER1", habitat_code = "OR", transect_number = "T01")

gif_maker(data = coral_dyn, lter_site = "LTER1", habitat_code = "OR", transect_number = "T02")

gif_maker(data = coral_dyn, lter_site = "LTER1", habitat_code = "OR", transect_number = "T03")

gif_maker(data = coral_dyn, lter_site = "LTER1", habitat_code = "OR", transect_number = "T04")

```

```{r}
gif_maker(data = coral_dyn, lter_site = "LTER2", habitat_code = "BR", transect_number = "T01")

gif_maker(data = coral_dyn, lter_site = "LTER2", habitat_code = "BR", transect_number = "T02")

gif_maker(data = coral_dyn, lter_site = "LTER2", habitat_code = "BR", transect_number = "T03")

gif_maker(data = coral_dyn, lter_site = "LTER2", habitat_code = "BR", transect_number = "T04")

gif_maker(data = coral_dyn, lter_site = "LTER2", habitat_code = "OR", transect_number = "T01")

gif_maker(data = coral_dyn, lter_site = "LTER2", habitat_code = "OR", transect_number = "T02")

gif_maker(data = coral_dyn, lter_site = "LTER2", habitat_code = "OR", transect_number = "T03")

gif_maker(data = coral_dyn, lter_site = "LTER2", habitat_code = "OR", transect_number = "T04")

```
```{r}
gif_maker(data = coral_dyn, lter_site = "LTER4", habitat_code = "BR", transect_number = "T01")

gif_maker(data = coral_dyn, lter_site = "LTER4", habitat_code = "BR", transect_number = "T02")

gif_maker(data = coral_dyn, lter_site = "LTER4", habitat_code = "BR", transect_number = "T03")

gif_maker(data = coral_dyn, lter_site = "LTER4", habitat_code = "BR", transect_number = "T04")

gif_maker(data = coral_dyn, lter_site = "LTER4", habitat_code = "OR", transect_number = "T01")

gif_maker(data = coral_dyn, lter_site = "LTER4", habitat_code = "OR", transect_number = "T02")

gif_maker(data = coral_dyn, lter_site = "LTER4", habitat_code = "OR", transect_number = "T03")

gif_maker(data = coral_dyn, lter_site = "LTER4", habitat_code = "OR", transect_number = "T04")

```
```{r}
gif_maker(data = coral_dyn, lter_site = "LTER5", habitat_code = "BR", transect_number = "T01")

gif_maker(data = coral_dyn, lter_site = "LTER5", habitat_code = "BR", transect_number = "T02")

gif_maker(data = coral_dyn, lter_site = "LTER5", habitat_code = "BR", transect_number = "T03")

gif_maker(data = coral_dyn, lter_site = "LTER5", habitat_code = "BR", transect_number = "T04")

gif_maker(data = coral_dyn, lter_site = "LTER5", habitat_code = "OR", transect_number = "T01")

gif_maker(data = coral_dyn, lter_site = "LTER5", habitat_code = "OR", transect_number = "T02")

gif_maker(data = coral_dyn, lter_site = "LTER5", habitat_code = "OR", transect_number = "T03")

gif_maker(data = coral_dyn, lter_site = "LTER5", habitat_code = "OR", transect_number = "T04")
```

